name: Petclinc frontend CI/CD for develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
   # container:
   #   image: node:14.15.1-alpine
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build . -t  spring-petclinic-angular:latest
      - name: run container from docker image
        run: docker run -p 8080:8080 --detach --name petclinc-frontend-container spring-petclinic-angular:latest
 #     - name: Install Node.js/npm on Docker Image
 #       run: docker exec --workdir /spring-petclinic-angular/ petclinc-frontend-container apk add --update npm
 #     - name: Install Dependencies with npm in docker container
 #       run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container npm install
      - name: Run Unit-Tests (Karma)
        run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container npm run test
    #  - name: Run E2E-Tests(cypress)
    #    run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container npm run e2e

#jobs:
#  ci:
#    runs-on: ubuntu-latest
#    container:
#      image: node:14.15.1-alpine
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install
#        run: npm install
#      - name: Tests
#        run: npm test


